### ISSUE TITLE
Generating a new USER key deletes all other key for that user.

### ISSUE THREAD

**Issue by eddiewebb** [Libertymutual/ssh-key-enforcer-stash#12]
Right now it calls Stash service to purge all instead of getting list of user keys and purging specifically.

https://github.com/Libertymutual/ssh-key-enforcer-stash/blob/master/src/main/java/com/lmig/forge/stash/ssh/keys/EnterpriseSshKeyServiceImpl.java#L98

Generating a new user Key via our custom UI should only destroy existing user keys.

**Comment by jdesulme** [comment]
The changes look good especially since you're just removing my user key. Now I'm guessing this also means that by default I will be apart of that 90 day policy to change my key?

**Comment by eddiewebb** [comment]
Only the ones you create in stash. Ones you create in bamboo aren't enforced right now.
