### ISSUE TITLE
Update Stash SSH Key Enforcer plugin to work with Bitbucket

### ISSUE THREAD

**Issue by jdesulme** [Libertymutual/ssh-key-enforcer-stash#17]
The plugin now needs to be updated to support Bitbucket. 

https://confluence.atlassian.com/bitbucketserver/how-to-update-your-add-on-779302412.html

**Comment by eddiewebb** [comment]
Pull requests welcome😉

I'll try to carve out time this weekend though

**Comment by jdesulme** [comment]
I'll take a crack at it too. Just wanted to put this on your radar as we're still a couple weeks away from getting a new version built out.

**Comment by eddiewebb** [comment]
Had to update a number of components (AO, Test-Runner, etc) and changed all miorated types based on the link @jdesulme shared.

Running some exploratory tests against a cluster (see #19 ) locally before I open a PR for this.
